name: Lint check
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      # Check out current repo
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@master
        env:
          # SHELLCHECK_OPTS: # uncomment to set shellcheck options
          SHFMT_OPTS: -ln bash -i 2 -ci # arguments to shfmt.

  py-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Set up basic Python installation
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install isort / flake8 / black
        run: |
          pip install isort flake8 black
      - name: Run isort
        run: |
          isort --check-only water_nes
      - name: Run black
        run: |
          black water_nes --check
      - name: Run flake8
        run: |
          flake8 --max-line-length 88 water_nes
