name: Test
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out current repo
      - name: Checkout current repository
        uses: actions/checkout@v3
      # Prepare a minimal environment
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: 3.9
          activate-environment: test
          channel-priority: true
          environment-file: devtools/conda-envs/test_env.yml
          auto-activate-base: false
      # Install pmx from the (py3 compatible) develop branch
      - name: Install pmx
        shell: bash
        run: |
          pip install git+https://github.com/deGrootLab/pmx.git@develop
      # Get more information about environment
      - name: Environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      # Test that simulations run without error
      - name: Run simulations
        shell: bash -l {0}
        run: |
          bash tests/test_run_simulations.sh
      # Run Python tests
      - name: Run Python tests
        shell: bash -l {0}
        run: |
          pytest tests/
